version: '3'
services:
  apache2:
    build: .
    hostname: yourserver.com
    restart: always
    volumes:
      - etcletsencrypt:/etc/letsencrypt
      - varletsencrypt:/var/lib/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    environment:
      LETS_ENCRYPT_EMAIL: "your@email.com"
      LETS_ENCRYPT_DOMAINS: "yourserver.com,www.yourserver.com,site2.yourserver.com"

volumes:
  varletsencrypt:
  etcletsencrypt:
